name: Release

on:
  workflow_dispatch:

jobs:
  npm:
    name: Go Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Git
        run: |
          git config --global user.name GitHub Actions
          git config --global user.email J-R-Oliver@users.noreply.github.com
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Generate Changelog
        run: npx standard-version --skip.bump
      - name: Commit Changelog & tag
        run: git push --tags origin HEAD:main
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
